#!/usr/bin/env python3

import mysql.connector

cnx = mysql.connector.connect(
    host = "localhost",
    user = "root",
    # password = ""
)

cursor = cnx.cursor()   # create a cursor

# query db is existing or not
cursor.execute("show databases like 'db'")
result = cursor.fetchone()

if result:
    cursor.execute("use db")
    cursor.execute("drop database db")
    print("db delete successfully")
else:
    print("db not exists, skip delete\n")

cursor.execute("create database if not exists db")
cnx.commit()

cursor.execute("use db")    # use db

sql_colleges = "create table if not exists `college` ( \
                college_id int(11) not null auto_increment primary key, \
                college_name varchar(20) not null, \
                employ_rate float(11), \
                sex_radio float(11), \
                der float(11), \
                oer float(11), \
                keyword varchar(20), \
                student_num int(11), \
                province_name varchar(20) not null, \
                popularity float(11) \
                )"

sql_users = "create table if not exists `user` ( \
            user_id int(11) not null auto_increment primary key, \
            user_name varchar(20) not null, \
            password varchar(20) not null, \
            sex varchar(20) not null, \
            grade float(11) not null, \
            province_name varchar(20) not null, \
            des_major varchar(20) not null, \
            des_province varchar(20) not null, \
            des_college varchar(20) not null \
            )"

sql_major = "create table if not exists `major` ( \
            major_id int(11) not null auto_increment primary key, \
            major_name varchar(20) not null \
            )"

sql_major_info = "create table if not exists `major_info` ( \
                  college_id int(11) not null auto_increment, \
                  major_id int(11) not null, \
                  level varchar(10) not null, \
                  primary key (college_id, major_id) \
                  )"

sql_relation = "create table if not exists `relation` ( \
                college_id int(11) not null auto_increment, \
                province_name varchar(20) not null, \
                year int(11) not null, \
                lowest_grade float(11) not null, \
                lowest_ranking int(11) not null, \
                enroll_num int(11) not null, \
                primary key (college_id, province_name, year) \
                )"

sql_major_enroll = "create table if not exists `major_enroll` ( \
                    college_id int(11) not null auto_increment, \
                    province_name varchar(20) not null, \
                    major_id int(11) not null, \
                    year int(11) not null, \
                    grade float(11) not null, \
                    primary key (college_id, province_name, major_id, year) \
                    )"

province = "create table if not exists `province` ( \
            province_id not null auto_increment, \
            province_name not null, \
            college_num not null\
            )"

cursor.execute(sql_colleges)
cursor.execute(sql_major)
cursor.execute(sql_major_enroll)
cursor.execute(sql_major_info)
cursor.execute(sql_relation)
cursor.execute(sql_users)

cursor.close()
cnx.close()