#!/usr/bin/env python3

import mysql.connector
from mysql.connector import errorcode

try:

    cnx = mysql.connector.connect(
        host = "localhost",
        user = "root",
        # password = ""
        database = "db"
    )

    cursor = cnx.cursor()   # create a cursor

    cnx.start_transaction() # start a transaction

    province_datas = [
        {
            "province_name": "四川",
            "college_num": 134
        },
        {
            "province_name": "重庆",
            "college_num": 69
        },
    ]

    def insert_province (province_data):
        cursor.execute("insert into province(province_name, college_num) values ('{}', {})".format(province_data["province_name"], province_data["college_num"]))

    for i in province_datas:
        insert_province(i)

    print("Insert province data successfully!")

    college_datas = [
        {
            "college_name": "四川大学",
            "employ_rate": 0.88,
            "sex_radio": 1.07,
            "der": 0.509,
            "oer": 0.1016,
            "keyword": "双一流、文理兼强、中等偏上",
            "province_name": "四川",
            "popularity": 33061066
        },
    ]

    def insert_college(college_data):
        cursor.execute("insert into college(college_name, employ_rate, sex_radio, der, oer, keyword, province_name, popularity) \
                       values ('{}','{}','{}','{}','{}','{}','{}','{}')".format
                       (college_data["college_name"], college_data["employ_rate"],college_data["sex_radio"],college_data["der"],college_data["oer"],college_data["keyword"],college_data["province_name"],college_data["popularity"]))

    for i in college_datas:
        insert_college(i)

    print("Insert college data successfully!")

    major_datas = [ 
        {
            "major_name": "数学"
        }
    ]

    def insert_major(major_data):
        cursor.execute("insert into major(major_name) values ('{}')".format(major_data["major_name"]))

    for i in major_datas:
        insert_major(i)

    print("Insert major data successfully!")


    major_info_datas = [
        {
            "college_name": "四川大学",
            "major_name": "口腔医学",
            "level": "A+",
        }
    ]

    for i in major_info_datas:
        college_id = cursor.execute("select college_id from college where college_name = '{}'".format(i["college_name"]))
        major_id = cursor.execute("select major_id from major where major_name = '{}'".format(i["major_name"]))
        cursor.execute("insert into major_info(college_id, major_id, level) values ('{}','{}','{}')".format(college_id, major_id, i["level"]))

    print("Insert major_info data successfully!")

    relation_datas = [
        {
            "college_name": "重庆大学",
            "province_name": "北京",
            "year_array": [
                2022,
                2021,
                2020,
            ],
            "lowest_grade_array": [
                610,
                616,
                616,
            ],
            "lowest_ranking_array": [
                6509,
                7612,
                8400,
            ],
            "enroll_num_array": [
                21,
                15,
                22,
            ]
        },
    ]

    def insert_relation(relation_data):
        college_id = cursor.execute("select college_id from college where college_name = '{}'".format(relation_data["college_name"]))
        province_id = cursor.execute("select province_id from province where province_name = '{}'".format(relation_data["province_name"]))
        for i in range(len(relation_data["year_array"])):
            cursor.execute("insert into relation(college_id, province_id, year, lowest_grade, lowest_ranking, enroll_num) \
                            values ('{}','{}','{}','{}','{}','{}')".format(college_id, province_id, relation_data["year_array"][i], relation_data["lowest_grade_array"][i], relation_data["lowest_ranking_array"][i], relation_data["enroll_num_array"][i]))
            
    for i in relation_datas:
        insert_relation(i)

    print("Insert relation data successfully!")

    major_enroll_datas = [
        {
            "college_name": "北京大学",
            "province_name": "北京",
            "year_array": [
                2022,
            ],
            # the length of majors_info_array must be equal to the length of year_array
            "majors_info_array": [
                [
                    {
                        "major_name": "数学",
                        "major_grade": 688,
                        "major_ranking": 390,
                    },
                ]
            ]
        }
    ]

    def insert_major_enroll(major_enroll_data):
        college_id = cursor.execute("select college_id from college where college_name = '{}'".format(major_enroll_data["college_name"]))
        for i in range(len(major_enroll_data["year_array"])):
            for j in range(len(major_enroll_data["majors_info_array"])):
               cursor.execute("insert into major_enroll(college_id, year, major_name, major_grade, major_ranking) \
                                 values ('{}','{}','{}','{}','{}')".format(college_id, major_enroll_data["year_array"][i], major_enroll_data["majors_info_array"][i][j]["major_name"], major_enroll_data["majors_info_array"][i][j]["major_grade"], major_enroll_data["majors_info_array"][i][j]["major_ranking"]))

    for i in major_enroll_datas:
        insert_major_enroll(i)

    print("Insert major_enroll data successfully!")

    cnx.commit()    # commit the transaction
    print("Transaction commit successfully!")

except mysql.connector.Error as err:
    cnx.rollback()
    print(f"Transaction rollback due to err: {err}")

finally:
    cursor.close()
    cnx.close()